name: Sync GitHub Projects

on:
  schedule:
    - cron: "0 0 * * *" # every day at 00:00 UTC
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: portfolio
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: portfolio/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Sync projects from GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          node scripts/fetch_github.js sk-0908 --include-forks --include-archived --max 100

      - name: Commit changes if any
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain src/data/projects.json)" ]; then
            git add src/data/projects.json
            git commit -m "chore(data): sync projects from GitHub"
            git push
          else
            echo "No changes to commit"
          fi

